# ------------------------------------------------------------ #
[potential]
potential_name = "SchNet"
# ------------------------------------------------------------ #
[potential.core_parameter]
number_of_radial_basis_functions = 300
maximum_interaction_radius = "30.0 angstrom"
number_of_interaction_modules = 3
number_of_filters = 64
shared_interactions = false
predicted_properties = ["per_atom_energy"]
predicted_dim = [1]
# ------------------------------------------------------------ #
[potential.core_parameter.activation_function_parameter]
activation_function_name = "ShiftedSoftplus"
# ------------------------------------------------------------ #
[potential.core_parameter.featurization]
properties_to_featurize = ['atomic_number']
[potential.core_parameter.featurization.atomic_number]
maximum_atomic_number = 100
number_of_per_atom_features = 64
# ------------------------------------------------------------ #
[potential.postprocessing_parameter]
properties_to_process = ['per_atom_energy']
[potential.postprocessing_parameter.per_atom_energy]
normalize = false
from_atom_to_molecule_reduction = true
keep_per_atom_property = true
