[training]
number_of_epochs = 200
remove_self_energies = true
batch_size = 64
lr = 5e-4
monitor = "val/per_system_energy/rmse" # Common monitor key
shift_center_of_mass_to_origin = false
plot_frequency = 1
# ------------------------------------------------------------ #
[training.experiment_logger]
logger_name = "wandb"
[training.experiment_logger.wandb_configuration]
save_dir = "logs"
project = "train_potentials"
group = "exp00"              # use this to group different experiments
log_model = true
job_type = "testing"
tags = ["v_0.1.0"]
notes = "testing training"
# ------------------------------------------------------------ #
[training.lr_scheduler]
scheduler_name = "ReduceLROnPlateau"
frequency = 1
mode = "min"
factor = 0.1
patience = 25
cooldown = 10
min_lr = 1e-8
threshold = 0.1
threshold_mode = "abs"
interval = "epoch"
# ------------------------------------------------------------ #
[training.loss_parameter]
loss_components = ['per_system_energy']
[training.loss_parameter.weight]
per_system_energy = 1.0
# ------------------------------------------------------------ #
[training.early_stopping]
verbose = true
min_delta = 0.05
patience = 100
# ------------------------------------------------------------ #
[training.splitting_strategy]
name = "random_record_splitting_strategy"
data_split = [0.8, 0.1, 0.1]
seed = 42
# ------------------------------------------------------------ #
