[potential]
model_name = "ANI2x"

[potential.potential_parameter]
angle_sections = 4
radial_max_distance = "5.1 angstrom"
radial_min_distance = "0.8 angstrom"
number_of_radial_basis_functions = 16
angular_max_distance = "3.5 angstrom"
angular_min_distance = "0.8 angstrom"
angular_dist_divisions = 8
