[potential]
model_name = "PhysNet"

[potential.potential_parameter]
max_Z = 101
number_of_atom_features = 64
number_of_radial_basis_functions = 16
cutoff = "5.0 angstrom"
number_of_interaction_residual = 3
number_of_modules = 5
