[potential]
model_name = "SAKE"

[potential.potential_parameter]
max_Z = 101
number_of_atom_features = 64
number_of_radial_basis_functions = 50
cutoff = "5.0 angstrom"
number_of_interaction_modules = 6
number_of_spatial_attention_heads = 4
