[potential]
model_name = "SchNet"

[potential.potential_parameter]
max_Z = 101
number_of_atom_features = 32
number_of_radial_basis_functions = 20
cutoff = "5.0 angstrom"
number_of_interaction_modules = 3
number_of_filters = 32
shared_interactions = false
